name: Pull Request Checks

on:
  push:
    branches: [ '**' ]  # Run on all branches
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ '**' ]  # Run on PRs to any branch
  workflow_dispatch:  # Allow manual triggering
  schedule:
    - cron: '0 14 * * *'  # Run daily at 2 PM UTC

jobs:
  pr-validation:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout PR
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for comparisons
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
        cache: 'yarn'
    
    - name: Install dependencies
      run: yarn install --frozen-lockfile
      
    - name: Check code formatting
      run: |
        echo "=== Checking code formatting ==="
        npx prettier --check "src/**/*.{ts,html,scss,json}" || true
        
    - name: Run linting
      run: yarn ng lint
      
    - name: Type checking
      run: npx tsc --noEmit
      
    - name: Run tests
      run: yarn ng test --watch=false --browsers=ChromeHeadless
      
    - name: Build check
      run: yarn ng build --configuration=production
      
    - name: Bundle size comparison
      run: |
        # Build base branch
        git checkout ${{ github.base_ref }}
        yarn install --frozen-lockfile
        yarn ng build --configuration=production
        BASE_SIZE=$(du -sb docs | cut -f1)
        
        # Build PR branch
        git checkout ${{ github.head_ref }}
        yarn install --frozen-lockfile
        yarn ng build --configuration=production
        PR_SIZE=$(du -sb docs | cut -f1)
        
        # Calculate difference
        DIFF=$((PR_SIZE - BASE_SIZE))
        PERCENT=$((DIFF * 100 / BASE_SIZE))
        
        echo "=== Bundle Size Comparison ==="
        echo "Base branch size: $BASE_SIZE bytes"
        echo "PR branch size: $PR_SIZE bytes"
        echo "Difference: $DIFF bytes ($PERCENT%)"
        
        if [ $PERCENT -gt 10 ]; then
          echo "⚠️ Bundle size increased by more than 10%"
        elif [ $PERCENT -lt -10 ]; then
          echo "✅ Bundle size decreased by more than 10%"
        else
          echo "✅ Bundle size change is within acceptable range"
        fi
      continue-on-error: true
      
    - name: Comment PR results
      uses: actions/github-script@v7
      if: always()
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '✅ PR checks completed. See workflow details for results.'
          })
